---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-1804-default
    image: solita/ubuntu-systemd:18.04
    privileged: true
    command: /sbin/init
provisioner:
  log: true
  name: ansible
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
  options:
    vvv: True
verifier:
  name: testinfra
  directory: ../resources/tests/
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
lint: |
  set -e
  yamllint .
  flake8
